# site settings
title: Alejandro
subtitle: Bicelis
email: me@alejandrobicelis.ca
# description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://alejandrobicelis.ca/

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 100

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  LinkedIn: https://www.linkedin.com/in/alejandro-bicelis-2a8a6418
  Envelope: mailto:me@alejandrobicelis.ca
  GitHub: https://github.com/abicelis
  Google: https://play.google.com/store/apps/developer?id=Alejandro+Bicelis
  Instagram: https://www.instagram.com/seed_87
  Twitter: https://twitter.com/seed_87

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- generic.md
- landing.md
- elements.md
- all_posts.md
